### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by crablab** [filiptypjeu/npm-ipp-easyprint#2]
Hey! :wave:  

Just looking around this project and wondered if there was any documentation planned/in the works? It would really help to have a minimal usage/getting started :+1:  

Very happy to help contribute, if that is useful!

**Comment by filiptypjeu** [comment]
Hi, sorry for the delay.

I made this project for myself and my own needs, and I didn't think anyone else would be interested in it. That being said, I appreciate your interest and have provided the project with some documentation!

Enjoy!

**Comment by crablab** [comment]
Thanks!
